on: pull_request
name: Pull Request Review
jobs:
  frontend-build:
    name: Frontend build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make build dir
        run: |
          mkdir -p build

      - name: Build assets
        run: |
          docker network create frontend
          docker compose run --rm node yarn install
          docker compose run --rm node yarn build

  frontend-coding-standards:
    name: Frontend coding standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: React coding standards
        run: |
          docker network create frontend
          docker compose run --rm node yarn install
          docker compose run --rm node yarn check-coding-standards

  cypress:
    name: Cypress
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: ["chrome"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup network
        run: docker network create frontend

      - name: Install client
        run: docker compose run node yarn

      - name: Cypress run
        run: docker compose run cypress run --browser ${{ matrix.browser }}

      - name: Archive screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots
          retention-days: 7

  changelog:
    runs-on: ubuntu-latest
    name: Changelog should be updated
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Git fetch
        run: git fetch

      - name: Check that changelog has been updated.
        run: git diff --exit-code origin/develop -- CHANGELOG.md && exit 1 || exit 0
